### ISSUE TITLE
Intersecting inner is ignored

### ISSUE THREAD

**Issue by nlehuby** [osm-without-borders/cosmogony#49]
This part of admin is an enclave : https://www.openstreetmap.org/way/137109677
It is part of the city [Pieve del Cairo](https://www.openstreetmap.org/relation/44019), whereas it is fully inside the city of [Isola Sant'Antonio](https://www.openstreetmap.org/relation/44002).

In Cosmogony, the enclave is is both cities :-1: 
This may be because the enclave shares one point ([one node](https://www.openstreetmap.org/node/1503882940)) with one of the city boundary.

![inclusion](https://user-images.githubusercontent.com/919962/41398376-70d14b20-6fb7-11e8-949d-88f5ffb3b998.gif)

**Comment by amatissart** [comment]
This is indeed due to a bug in how inner boundaries are associated to outer ones when building multipolygons in osm_boundaries_utils.

Here is a fix I suggest: https://github.com/QwantResearch/osm_boundaries_utils_rs/pull/6
