### ISSUE TITLE
Bruxelles region not shown

### ISSUE THREAD

**Issue by ThomasG77** [osm-without-borders/cosmogony#70]
When I browse to http://cosmogony.world/#/7.59/4.26/50.80/168112 and I switch to "Country region", I get an empty region for Bruxelles (normally, it's admin_level=4) but I see the two other regions Flanders and Wallonie (both admin_level=4)
See 1st screenshot 
![selection_905](https://user-images.githubusercontent.com/642120/49930054-23a71e00-fec4-11e8-87ff-e4273a1f8610.png)
Then, I choose "State". I see Bruxelles area not empty and when I click on "Bruxelles", I get the polygon with admin_level=4 I was expecting one level above (at "Country region"). See 2nd screenshot
![selection_906](https://user-images.githubusercontent.com/642120/49930304-9617fe00-fec4-11e8-8696-c8589485cb40.png)
It doesn't seem normal. Can you confirm it's an issue?

**Comment by nlehuby** [comment]
Cosmogony relies on a mapping between OSM `admin_level` and a few admin types (`state`, `state_district`, etc) and not directly on `admin
_level` tag.

Here is the config file used for Belgium on cosmogony.world: https://github.com/osm-without-borders/libpostal/blob/5bcae28fe4bdf42c905661d6e594a55a0d2113d8/resources/boundaries/osm/be.yaml
It has an exception to set Brussels-Capital Region as a `state`, which explains what you can see in the explorer.

cosmogony.world is not up to date with the last config changes yet, here is the new one for Belgium country: https://github.com/osm-without-borders/libpostal/blob/master/resources/boundaries/osm/be.yaml

Does this look better for you ?

**Comment by ThomasG77** [comment]
Need to deploy to confirm the expected behavior. Then, will close if OK. Thanks for your fast answer.

**Comment by nlehuby** [comment]
We have some work in progress to enhance the deployment process so you will have to wait for a while, sorry :sad:

If you want to run it by yourself, check out [our new doc](https://github.com/osm-without-borders/cosmogony_explorer#Usage).

**Comment by frodrigo** [comment]
Can be closed. It look OK for me now.

**Comment by ThomasG77** [comment]
Thanks for the verification
