### ISSUE TITLE
http://cosmogony.world not accessible

### ISSUE THREAD

**Issue by bdon** [osm-without-borders/cosmogony#97]
I'm not able to access the website - is this service still running or are there any DNS issues?

**Comment by amatissart** [comment]
Thanks for raising the issue, it's now back online.

I must say that we had little time to maintain the explorer. Data appearing on cosmogony.world have not been updated recently and may not reflect latest openstreetmap data.

**Comment by bdon** [comment]
@amatissart thanks, it's working great now. Is there a way to download the processed geometries as GeoJSON etc?
